### ISSUE TITLE
Update to use newer version of Ruby

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/rails-blog-scaffold#2]
This may be the first lab that requires Ruby 2.2.0. Lots of old gems here, too.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by changamanda** [comment]
Bumped Ruby version, but I don't know if you want to close this. Probably still old gems?

**Comment by NoneOfMaster** [comment]
The bundle fails and the specs won't run:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/me/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20160117-1346-17gvcsj.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/russelltepper/.rvm/rubies/ruby-2.2.2/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in /Users/me/.rvm/gems/ruby-2.2.2/gems/pg-0.18.1 for inspection.
Results logged to /Users/me/.rvm/gems/ruby-2.2.2/extensions/x86_64-darwin-14/2.2.0/pg-0.18.1/gem_make.out
An error occurred while installing pg (0.18.1), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.1'` succeeds before bundling.
